import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import sonarjs from "eslint-plugin-sonarjs";
import reactCompiler from "eslint-plugin-react-compiler";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Claude Code agent worktrees — not project source
    ".claude/**",
    // Generated workflow bundle — regenerated by withWorkflow on build, not source
    "app/.well-known/**",
  ]),
  // Clean Code rules for all source files
  {
    plugins: { sonarjs },
    rules: {
      // Long functions = too many responsibilities (Uncle Bob; 50 is a practical gate)
      "max-lines-per-function": ["warn", { max: 50, skipBlankLines: true, skipComments: true }],
      // High cyclomatic complexity = hard to test and understand
      complexity: ["warn", 10],
      // Too many parameters = function does too many things
      "max-params": ["warn", 4],
      // Hard-to-read deeply nested logic
      "sonarjs/cognitive-complexity": ["warn", 15],
      // Duplicate string literals — extract to named constants
      "sonarjs/no-duplicate-string": ["warn", { threshold: 3 }],
      // Copy-pasted functions — extract to shared helper
      "sonarjs/no-identical-functions": "warn",
      // Honour the `_`-prefix convention for intentionally-unused vars/args
      // (e.g. `const { members: _members, ...rest } = list` to omit a key)
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
  // React Compiler — flags components that violate the Rules of React (compiler bails on them)
  {
    plugins: { "react-compiler": reactCompiler },
    rules: { "react-compiler/react-compiler": "error" },
  },
  // Relax rules for test files — fixture strings and long describe blocks are expected
  {
    files: ["lib/__tests__/**", "**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts"],
    rules: {
      "max-lines-per-function": "off",
      "sonarjs/no-duplicate-string": "off",
      complexity: "off",
      "sonarjs/cognitive-complexity": "off",
    },
  },
  // e2e infrastructure: globalThis container passing requires `any` (no clean alternative
  // without a full global type declaration for testcontainer lifecycle hooks)
  {
    files: ["e2e/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
]);

export default eslintConfig;
